### ISSUE TITLE
Children can only be passed as attributes

### ISSUE THREAD

**Issue by ALMaclaine** [krakenjs/jsx-pragmatic#1]
First of all thank you, this is a really interesting and promising library.

I'm trying to get the hang of the library and was setting up some basic components. Unless I'm messing something, children can only be passed as attributes:

For Example:
```<ActionItem className="ASD DSA SDA" ariaLabel="Download" children="file_download" />```

Works and children inside action item is "file_download"

```<ActionItem className="ASD DSA SDA" ariaLabel="Download">file_download</ActionItem>``` 

does not work, children is undefined.

Here is ActionItem

```
import { node } from 'jsx-pragmatic';

interface DestructTypes {
  className: string;
  ariaLabel: string;
  children: string | Element;
};

export default function ActionItem({ className, ariaLabel, children }: DestructTypes) {
  const classes = "material-icons mdc-top-app-bar__action-item " + className;
  console.log(children);
  return (
    <a
    href="#"
    className={classes}
    aria-label={ariaLabel}>
      {children}
    </a>
  );
}
```

Thanks

**Comment by bluepnume** [comment]
`children` should be passed as a second argument to `ActionItem` -- so you should be able to do: `function ActionItem({ className, ariaLabel }, children)`

**Comment by ALMaclaine** [comment]
Awesome, works perfectly, thank you for the swift reply and again thank you for the library.

**Comment by ALMaclaine** [comment]
I realized after closing the issue, but isn't this out of step with the React API where children is on the props variable?

https://reactjs.org/docs/composition-vs-inheritance.html#containment

Is there any particular reason this decision was made and will it persist?

**Comment by ALMaclaine** [comment]
I realized after closing the issue, but isn't this out of step with the React API where children is on the props variable?

https://reactjs.org/docs/composition-vs-inheritance.html#containment

Is there any particular reason this decision was made and will it persist?
