### ISSUE TITLE
render with container id throws TypeError

### ISSUE THREAD

**Issue by gutisalex** [krakenjs/jsx-pragmatic#15]
Hey, I am trying to add some html to a div container like in the paypal checkout with the button. I used the demo for that but unfortunately its not working.

### index.html

```
<head>
	<title>JSX Pragmatic Dev Demo</title>
</head>

<body>
  <div id="test"></div>
  <script src="/jsx-pragmatic-demo.js"></script>
</body>
```

### index.jsx:

```
/* @flow */
/* @jsx node */

import { node, dom } from '../../src';

export function login() {

  return (
    <section>
      <input type="text" placeholder="email" />
      <input type="password" placeholder="password" />
      <button>Log In</button>
    </section>
  );
}

// console.log(login());
login().render('#test')
```

### Output
```
Uncaught TypeError: renderer is not a function
    at ElementNode._proto.render (VM1088 jsx-pragmatic-demo.js:97)
    at Module.<anonymous> (VM1088 jsx-pragmatic-demo.js:257)
    at __webpack_require__ (VM1088 jsx-pragmatic-demo.js:13)
    at VM1088 jsx-pragmatic-demo.js:61
    at VM1088 jsx-pragmatic-demo.js:62
    at VM1088 jsx-pragmatic-demo.js:2
    at VM1088 jsx-pragmatic-demo.js:3
```

And another question: When using with dom() I only get the code back when console.logging it. I thought it would render to to page automatically?!

**Comment by mnicpt** [comment]
@gutisalex Will take a look at this and let you know what I find.  Thank you for raising this issue.

**Comment by mnicpt** [comment]
@gutisalex The error you are receiving is because you must pass in a supported renderer function or a custom renderer into the render function.  The render function returns the node for the renderer you use, so you need to store it off into a variable and use it.  That's why you see it in the console.log.  It does not render to another DOM element of your choosing.  If you want to do that in the example above, you can set the innerHTML of the target container to be the result of calling render.

**Comment by gutisalex** [comment]
Ok thanks for the quick reply... So I need to make a custom renderer when I want to pass the id of the container where I want the result to be rendered in? Do you have an example how its made in the paypal-checkout-components rep? In the SDK you can render it like `paypal.Buttons().render("paypal-button-container");` paypal being the name of the library Buttons() the function returning the node. I was searching the rep but could not find it!

**Comment by bluepnume** [comment]
Hey @gutisalex 

PayPal checkout actually uses https://github.com/krakenjs/zoid -- that gives the `Buttons().render('#container')` api.

With jsx-pragmatic, to render and insert into the DOM you would need to do something like this:

```javascript
/* @jsx node */

import { node, dom } from 'jsx-pragmatic';

export function login() {
  return (
    <section>
      <input type="text" placeholder="email" />
      <input type="password" placeholder="password" />
      <button>Log In</button>
    </section>
  );
}

const element = login().render(dom());
document.querySelector('#container').appendChild(element);
```

**Comment by gutisalex** [comment]
Ah so zoid is taking care of that... ok I think now I got it! I was literaly thinking its a pragmatic feature! Ok thanks mate, I think I know now how to do it... have a good one!
