### ISSUE TITLE
Create TypeScript typings

### ISSUE THREAD

**Issue by mstuart** [krakenjs/jsx-pragmatic#16]
This project isn't written in TypeScript, but many TypeScript users would like to use published typings. For this issue, create TypeScript typings that cover the exported functions, and contribute it back to DefinitelyTyped!

This issue is great for someone who wants to learn more about TypeScript!

**Comment by aayushbisen** [comment]
Hey I would like to work on this!

**Comment by iam-agf** [comment]
I'm just that person that wants to learn more about TypeScript, can I try this?

**Comment by mstuart** [comment]
Sure! All yours @iam-agf

**Comment by iam-agf** [comment]
I was having some issues even running certain content of the repository. I made a PR last time adding a change in the `CONTRIBUTING.md` file because it's outdated. Do all the scripts in that file work properly? For example, the line `npm run-script cover` doesn't work properly. Can you check that before?

**Comment by mstuart** [comment]
Sorry, @iam-agf  😬. Those were placeholders generated by another package. I just updated CONTRIBUTING.md to a better state. The `test` task will output coverage stats and a coverage/ directory. Let me know if you're still interested in taking this Issue up!

**Comment by iam-agf** [comment]
Yes, I'm but I'm literally learning with this, so that's why this is taking me so much time 😅, sorry for that (if there is someone that can do it faster, you can assign it to him/her)

**Comment by mstuart** [comment]
No worries! Thanks @iam-agf !

**Comment by mstuart** [comment]
@lsmoura opened https://github.com/krakenjs/jsx-pragmatic/pull/20
