### ISSUE TITLE
How to handle events？

### ISSUE THREAD

**Issue by Sylvenas** [krakenjs/jsx-pragmatic#6]
Thanks for great project!

If only we can render jsx to html,so what is the different with string template.

**Comment by Sylvenas** [comment]
Is it must work with [@babel/plugin-transform-react-jsx](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-jsx)?

**Comment by edrpls** [comment]
I ran into this issue as well, it seems the[ html renderer doesn't support](https://github.com/krakenjs/jsx-pragmatic/blob/master/src/renderers/html.js#L39) functions.

I guess you could stringify your functions, but I think that partially defeats the purpose of this, alternatively, you could write your own renderer to handle functions, but that seems like entering the frameworks realm.

I would like to know too if there is a better way to handle this when using the html renderer.

**Comment by mnicpt** [comment]
@Sylvenas and @edrpls Sorry we are just getting back to you on this.  To support functions as a renderer you will need to create a custom renderer as outlined in the README to handle functions.
